import { StoreBranchModel } from './../interfaces/store-branches.interface';
import { StoreLocationModel } from '../interfaces/store-location.interface';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class StoreService {

  storeLocations: StoreLocationModel[];
  selectedStore: StoreLocationModel;
  constructor() { 
    this.init();
  }
  init(){
    this.storeLocations = [
      { title: 'ACE HARDWARE', src: 'assets/stores/Ace.png', branches: [
        { type: 'LUZON', name: 'ANGONO',address:'2/F SM Center Angono, Manila East Road, Brgy. San Isidro, Angono',contact:'0917-824-6350'} as StoreBranchModel,
        { type: 'LUZON', name: 'BACOOR',address:'L/GF SM City Bacoor, Tirona Highway, cor Emilio Aguinaldo Hwy, Brgy, Bacoor',contact:'0917-824-6031'} as StoreBranchModel,
        { type: 'LUZON', name: 'BAGUIO',address:'2/F SM City Baguio, Luneta Hill PH, Upper Session Rd, Baguio',contact:'0917-824-5793'} as StoreBranchModel,
        { type: 'LUZON', name: 'BALIWAG',address:' G/F SM City Baliwag, DRT Highway, Brgy. Pagala, Baliuag Bulacan',contact:'0917-824-5873'} as StoreBranchModel,
        { type: 'LUZON', name: 'BATANGAS',address:'2/F SM City Batangas, Brgy. Pallocan West, Batangas',contact:'0917-824-5597'} as StoreBranchModel,
        { type: 'LUZON', name: 'BRAVO CENTER TANAUAN',address:'Tanauan, Batangas',contact:'0920-957-7831'} as StoreBranchModel,
        { type: 'LUZON', name: 'CABANATUAN ',address:'2/F SM City Cabanatuan Along Maharlika Hway, Brgy. H Concepcion 3100, Cabanatuan City',contact:'0917-824-5878'} as StoreBranchModel,
        { type: 'LUZON', name: 'CABUYAO',address:'G/F Walter Mart Cabuyao, KM 47 National Hway, Brgy. Banlic, Cabuyao',contact:'(049) 530-0576'} as StoreBranchModel,
        { type: 'LUZON', name: 'CALAMBA',address:'SM City Calamba, 2/F San Cristobal Bridge, Real, Calamba, Laguna',contact:'0917-809-9678'} as StoreBranchModel,
        { type: 'LUZON', name: 'CAUAYAN',address:'2/F SM City Cauayan, National Highway, District II, Cauayan City, Isabela',contact:'0917-824-5865'} as StoreBranchModel,
        { type: 'LUZON', name: 'CENTER SQUARE MOLINO',address:'2/F Main Square Mall, 102 Molino Boulevard, Bacoor',contact:'(046) 436-3007'} as StoreBranchModel,
        { type: 'LUZON', name: 'CHERRY ANTIPOLO',address:'SM Cherry, 145 Marikina-Infanta Hwy, Antipolo',contact:'0999-2210949'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL CALAMBA',address:'4027 San Cristobal Bridge, Calamba, Laguna',contact:'0917-817-3883'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL IMUS',address:'G/F CityMall Imus, Brgy. Anabu, Imus Cavite, Cavite City',contact:'0999-221-0964'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL MAYOMBO',address:'Ground Floor, Citymall, Dagupan, Pangasinan',contact:'0917-852-3867'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL SORSOGON',address:'Brgy. Poblacion, Rizal St, Sorsogon City',contact:'0999-227-2732'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL TIAONG ',address:'G/F CityMall Tiaong, Maharlika Highway, Brgy Quezon Province PH, Tiaong',contact:'(042) 717-6207'} as StoreBranchModel,
        { type: 'LUZON', name: 'CITY MALL TARLAC',address:' G/F Citymall Tarlac, MacArthur Highway, Tarlac City, 2300 Tarlac',contact:'(045) 606-3654'} as StoreBranchModel,
        { type: 'LUZON', name: 'CLARK',address:'G/F SM City Clark, Clark Special Economic Zone, M.A. Roxas, Angeles Pampanga',contact:'0917-824-5941'} as StoreBranchModel,
        { type: 'LUZON', name: 'DASMARINAS',address:'L/GF SM City Dasmariñas, Governor\'s Drive, Palapala, Dasmariñas Cavite',contact:'(046) 432-3137'} as StoreBranchModel,
        { type: 'LUZON', name: 'FILINVEST FORA',address:'Upper Ground Floor, Fora Mall, Brgy. Silang Crossing East, Rotunda Junction, Emilio Aguinaldo Hwy, Tagaytay',contact:'(046) 416-7775'} as StoreBranchModel,
        { type: 'LUZON', name: 'GAISANO CAPITAL CALAPAN',address:'National Road, Brgy, Calapan, 5200 Oriental Mindoro',contact:'(043)288-2343'} as StoreBranchModel,
        { type: 'LUZON', name: 'GAISANO CAPITAL MASBATE',address:'Lower Ground floor, Gaisano Capital Masbate Brgy. Tugbo, Sitio Cagba, Quezon St. Crossing, Masbate City',contact:'0935-414-6585'} as StoreBranchModel,
        { type: 'LUZON', name: 'GREENFIELD CITY STA. ROSA',address:' Units 101- 109, Lower Ground Flr. Arcadia Drive Thru Block, Tagaytay Balibago rd. Greenfield Sta. Rosa City',contact:'(02) 8552-5390'} as StoreBranchModel,
        { type: 'LUZON', name: 'HARMONY VILLAGE MALL',address:'G/F 05-08, Harmony Village Mall, Olympia Street, San Pedro Laguna',contact:'0925-738-8546'} as StoreBranchModel,
        { type: 'LUZON', name: 'IMUS',address:'G/F SM Center Imus, Imus',contact:'(02) 8519-4609'} as StoreBranchModel,
        { type: 'LUZON', name: 'LEGAZPI',address:'Zone 9, Imelda Roces Ave, Legazpi City',contact:'(054) 742-4014'} as StoreBranchModel,
        { type: 'LUZON', name: 'LEMERY',address:' 2/F SM Center Lemery , Illustre Avenue Cor. Calle P. Gomez, Lemery',contact:'(043) 277-6418'} as StoreBranchModel,
        { type: 'LUZON', name: 'LIPA',address:'2/F SM City Lipa J.P. Laurel Highway, Brgy PH, Lipa',contact:'(043) 756-5433'} as StoreBranchModel,
        { type: 'LUZON', name: 'LUCENA',address:'2/F SM City Lucena Dalihaccan cor. Maharlika Hway, Brgy, Lucena',contact:'(042) 710-5948'} as StoreBranchModel,
        { type: 'LUZON', name: 'MAGIC MALL SAN CARLOS',address:'Roxas Blvd, San Carlos City, 2420 Pangasinan',contact:'0917-625-8803'} as StoreBranchModel,
        { type: 'LUZON', name: 'MARILAO',address:'2/F SM City Marilao Km. 21 McArthur Highway, Barangay Ibayo, Marilao Bulacan',contact:'0917-824-5567'} as StoreBranchModel,
        { type: 'LUZON', name: 'MASINAG',address:'2/F SM City Masinag, Marcos Highway, Brgy. Mayamot, Masinag, Antipolo',contact:'(02) 8655-1328'} as StoreBranchModel,
        { type: 'LUZON', name: 'MEGACENTER',address:'2/F SM MegaCenter Cabanatuan, General Tinio Street, Brgy. San Roque Norte, Cabanatuan City',contact:'(044) 940-4890'} as StoreBranchModel,
        { type: 'LUZON', name: 'MENDEZ',address:'Tagaytay - Nasugbu Hwy, Tagaytay, Cavite',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'MOLINO',address:' L/G SM City, Molino Rd, Molino IV, Bacoor',contact:'(046) 474-3033'} as StoreBranchModel,
        { type: 'LUZON', name: 'NAGA',address:'2/F SM City Naga, Barangay Triangulo CBD II, Naga',contact:'(02) 8250-8104'} as StoreBranchModel,
        { type: 'LUZON', name: 'NEWPOINT MALL ANGELES',address:'Entec 2, Entec 2, L/GF Newpoint Mall Bldg. Plaridel St. cor. Catalina St Sto. Rosario Angeles City 2009 Pampanga PH, Saint Joseph Street, Angeles, Pampanga',contact:'0925-738-9413'} as StoreBranchModel,
        { type: 'LUZON', name: 'OLONGAPO DOWNTOWN',address:'SM City Olongapo, E 16th St, Olongapo, Zambales',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'PAMPANGA',address:' G/F SM City Pampanga, Olongapo-Gapan Road, Lagundi, Mexico, Pampanga (East Wing) and San Jose, San Fernando, Pampanga',contact:'(045) 961-6847'} as StoreBranchModel,
        { type: 'LUZON', name: 'PRIMARK CABIAO',address:'G/F Primark Town Center Nueva Ecija PH, Jose Abad Santos Avenue, Cabiao',contact:'0927-957-8751'} as StoreBranchModel,
        { type: 'LUZON', name: 'PUREGOLD CALAPAN',address:'National Road, Brgy Mindoro Oriental PH, Calapan',contact:'(043) 288-2058'} as StoreBranchModel,
        { type: 'LUZON', name: 'PUREGOLD LAOAG',address:'26 S Fonacier, Laoag City, 2900 Ilocos Norte',contact:'0919-086-8202'} as StoreBranchModel,
        { type: 'LUZON', name: 'ROSALES',address:' G/F SM City Rosales, Rosales Pangasinan City',contact:'(075) 653-0218'} as StoreBranchModel,
        { type: 'LUZON', name: 'ROSARIO',address:'G/F SM City Rosario, Brgy. Tejero, Rosario Cavite City',contact:'(046) 489-1893'} as StoreBranchModel,
        { type: 'LUZON', name: 'SAN FERNANDO',address:'G/F SM City San Fernando, V. Tiomico St., Brgy. Poblacion, San Fernando City, Pampanga',contact:'(045) 435-0878'} as StoreBranchModel,
        { type: 'LUZON', name: 'SAN JOSE DEL MONTE ',address:' L/GF SM City San Jose Del Monte, Quirino Highway, Tungkong Mangga, San Jose Del Monte, Bulacan',contact:'(044) 769-9147'} as StoreBranchModel,
        { type: 'LUZON', name: 'SAN PABLO',address:'G/F SM City San Pablo, Maharlika Hway, Brgy, San Pablo City, Laguna',contact:'(049) 521-0025'} as StoreBranchModel,
        { type: 'LUZON', name: 'SM CENTER PULILAN',address:' 2/F SM Center Pulilan, Plaridel-Pulilan Diversion Rd, Pulilan, 3005 Bulacan',contact:'(044) 913-3234'} as StoreBranchModel,
        { type: 'LUZON', name: 'SM CITY OLONGAPO CENTRAL',address:'E 16th St, Olongapo, Zambales',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'SM CITY PUERTO PRINCESA',address:'U/GF SM City Puerto Princesa, Malvar, Cor Lacao St, Barangay San Miguel, Puerto Princesa',contact:'(048) 717-0008'} as StoreBranchModel,
        { type: 'LUZON', name: 'SM BATANGAS',address:' SM Hypermarket Batangas Along National Highway, Brgy. Balagtas, Batangas',contact:'(02) 8524-4519'} as StoreBranchModel,
        { type: 'LUZON', name: 'SM DAGUPAN',address:'167 Calasiao - Dagupan Rd, Calasiao, Dagupan, 2400 Pangasinan',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'SMC APALIT',address:' 2/F SM SaveMore Apalit PH, MacArthur Highway, Apalit Pampanga',contact:'0917-8245692'} as StoreBranchModel,
        { type: 'LUZON', name: 'SMC ILAGAN',address:'Pan-Philippine Hwy, Ilagan, 3300 Isabela',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'STA ROSA',address:'G/F SM City Sta. Rosa, Old National Highway, Santa Rosa',contact:'0917-824-6079'} as StoreBranchModel,
        { type: 'LUZON', name: 'TARLAC',address:'2/F SM City Tarlac, McArthur Highway, Brgy. San Roque, Tarlac City',contact:'(045) 606-0044'} as StoreBranchModel,
        { type: 'LUZON', name: 'TAYTAY',address:'SM Taytay, Manila East Rd, Dolores, Taytay',contact:'(02) 8661-2026'} as StoreBranchModel,
        { type: 'LUZON', name: 'TELABASTAGAN',address:'SM City Telabastagan, MacArthur Highway, Telabastagan, San Fernando Pampanga',contact:'0917-843-4144'} as StoreBranchModel,
        { type: 'LUZON', name: 'TRECE MARTIRES ',address:'L/GF SM City Trece Martires, Governors Drive cor. Capitol Road, San Agustin, Trece Martires, Cavite City, Cavite',contact:'(046) 235-2047'} as StoreBranchModel,
        { type: 'LUZON', name: 'TUGUEGARAO DOWNTOWN',address:'Luna Street, Corner, Tuguegarao, 3500 Cagayan',contact:'(078) 375-2310'} as StoreBranchModel,
        { type: 'LUZON', name: 'URDANETA CENTRAL ',address:'SM City Urdaneta Central, MacArthur Highway, Urdaneta, Pangasinan',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'VALDEZ CENTER',address:'L G/F, VYV Building, Valdez Center San Francisco San Nicolas City, 2901',contact:'(077) 772-0728'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART CABANATUAN ',address:' 2/F Waltermart Cabanatuan Brgy. Dicarma Nueva Ecija PH, Pan-Philippine Hwy, Cabanatuan City',contact:'(044)951-1101'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART BALANGA',address:' Roman Superhighway, City of Balanga Bataan',contact:'0917-087-1959'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART BALAYAN ',address:'Balayan Hi-Way ,cor Paz Street , Brgy. Caloocan, Balayan, Batangas City',contact:'(043) 774-7886'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART BATANGAS',address:' P. Burgos St, Brgy. Calicanto Rd, Batangas',contact:'0919-087-3849'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART CONCEPCION ',address:' G/F Waltermart Concepcion L. Cortez St Barangay Alfonso Concepcion City, 2316 Tarlac',contact:'(045) 606-3764'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART NASUGBU',address:' Barangay, Ground Floor, Waltermart Nasugbu, J P Laurel St, Nasugbu',contact:'0917-820-4260'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART PANIQUI',address:' G/F Waltermart Paniqui McArthur Highway Barangay Estacion Paniqui City, 2307 Tarlac',contact:'(045) 606-0053'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART STA ROSA BEL AIR ',address:'2F Waltermart Sta. Rosa Bel Air, Tagaytay Road Barangay, Pulong Santa Cruz, Santa Rosa',contact:'(049) 544-4164'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART SUBIC',address:'Barca National Highway Brgy, Subic City Zambales',contact:'0919-086-8201'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART TALAVERA ',address:'G/F Waltermart Talavera Brgy. La Torres Talavera City Nueva Ecija PH, 3114',contact:'(044) 951-5432'} as StoreBranchModel,
        { type: 'LUZON', name: 'WALTERMART TAYTAY',address:'G/F Waltermart Taytay, Ortigas Ave Ext, Taytay',contact:'(02) 8535-3744'} as StoreBranchModel,
        { type: 'LUZON', name: 'WIND RESIDENCES',address:'G/F Wind Residences, Emilio Aguinaldo Highway, Maharlika West Tagaytay City',contact:'(02) 8519-4257'} as StoreBranchModel,
        { type: 'LUZON', name: 'XENTRO MALL POLANGUI',address:'Pan-Philippine Hwy, Polangui, Albay',contact:''} as StoreBranchModel,
        { type: 'LUZON', name: 'XENTRO MALL SANTIAGO',address:'2 F Xentromall, Santiago, 3311 Isabela',contact:'(078) 305-0507'} as StoreBranchModel,

        {type:'NCR', name:'ACE EXPRESS BAY CITY MALL OF ASIA',address:'3rd Flr, SM Mall of Asia,  Seaside Boulevard, Mall of Asia Complex, Pasay',contact:''} as StoreBranchModel,
        {type:'NCR', name:'ACE EXPRESS NORTH EDSA',address:'L/GF SM City North Edsa, North Ave. Cor., EDSA Quezon City',contact:'(02) 8441-1451'} as StoreBranchModel,
        {type:'NCR', name:'AURA PREMIER',address:'L/GF SM Aura Premier, 26th St. cor. McKinley Parkway,, Brgy. Fort Bonifacio, Global City, Taguig',contact:'0917-824-5521'} as StoreBranchModel,
        {type:'NCR', name:'AYALA MALLS MARIKINA',address:'2/F Puregold Bldg., Ayala Malls Marikina, Liwasang Kalayaan, Brgy, Marikina',contact:'0917-819-6597'} as StoreBranchModel,
        {type:'NCR', name:'BICUTAN',address:'SM Bicutan, Dona Soledad Ave, Parañaque, 1700 Metro Manila, Parañaque',contact:'0917-824-5870'} as StoreBranchModel,
        {type:'NCR', name:'BROADWAY',address:'G/F SAVEMORE MARKET, EAST GATE ARCADE, BROADWAY CENTRUM AURORA BLVD, COR BROADWAY AVE., QUEZON CITY',contact:'0927-567-6867'} as StoreBranchModel,
        {type:'NCR', name:'CAPITOL COMMONS',address:'2/F Unimart Capitol Commons, Shaw Blvd, cor Meralco Ave, Pasig',contact:'0917-833-1421'} as StoreBranchModel,
        {type:'NCR', name:'CASH AND CARRY',address:'2/F Cash & Carry Mall, South Super H-way cor. Emilia Sts., Palanan Makati City, Makati',contact:'09992209873'} as StoreBranchModel,
        {type:'NCR', name:'CHERRY CONGRESSIONAL',address:'SM Cherry Congressional, Congressional Avenue, Brgy PH, Quezon City',contact:'(02) 8285-6063'} as StoreBranchModel,
        {type:'NCR', name:'CUBAO NON-DEPARTMENT STORE',address:'3/F SM Cubao, Araneta Commercial Center, Socorro, Cubao, Quezon City',contact:'(02) 8912-5622'} as StoreBranchModel,
        {type:'NCR', name:'FAIRVIEW',address:'G/F SM City Fairview Annex, Quirino Ave. cor. Regalado St. Fairview, Quezon City',contact:'(02) 8938-9011'} as StoreBranchModel,
        {type:'NCR', name:'FESTIVAL MALL',address:'Festival Supermall Alabang, Muntinlupa',contact:'(02) 8850-3908'} as StoreBranchModel,
        {type:'NCR', name:'FISHER MALL',address:'2/F Fisher Mall, Quezon Ave, cor Roosevelt Ave, Quezon City',contact:'(02) 8288-9699'} as StoreBranchModel,
        {type:'NCR', name:'GREENHILLS',address:'2/F V-Mall, Greenhills Shopping Center San Juan City',contact:'(02)8725-2669'} as StoreBranchModel,
        {type:'NCR', name:'GREENBELT',address:'G/F Greenbelt I Square, Ayala Commercial Center,, Paseo de Roxas cor. Legaspi St. Salcedo Village, Makati',contact:'(02) 8815-9465'} as StoreBranchModel,
        {type:'NCR', name:'JAZZ RESIDENCES',address:'Jazz Residence Corner Metropolitan Ave & Nicanor Garcia St,., Brgy Bel-Air Makati City, Makati',contact:'(02) 8815-1258'} as StoreBranchModel,
        {type:'NCR', name:'LAS PINAS',address:'L/GF SM Center Las Pinas, Alabang-Zapote Road, Las Pinas',contact:'(02) 8873-3549'} as StoreBranchModel,
        {type:'NCR', name:'LIGHT RESIDENCES',address:'2/F Light Mall Edsa corner Madison St., Barangay Barranca, Mandaluyong',contact:'(02) 8696-2473'} as StoreBranchModel,
        {type:'NCR', name:'MAKATI MALL',address:' 3/F SM City Makati Annex, Annex Bldg., Ayala Center, Makati',contact:'(02) 8892-5905'} as StoreBranchModel,
        {type:'NCR', name:'MALL OF ASIA',address:'G/F Entertainment Mall - South Wing, SM Mall of Asia, Seaside Boulevard, Mall of Asia Complex, Pasay',contact:'(02) 8556-0406'} as StoreBranchModel,
        {type:'NCR', name:'MANILA',address:'2/F, SM City Manila, PH, Natividad Lopez St, Ermita, Manila',contact:'(02) 8523-7876'} as StoreBranchModel,
        {type:'NCR', name:'MARIKINA',address:' 2/F SM City Marikina, Marcos Hwy, Bgy. Calumpang, Marikina',contact:'(02) 8477-1669'} as StoreBranchModel,
        {type:'NCR', name:'MARKET MARKET',address:'3/F Market Market, Bonifacio Global City, Taguig, Taguig',contact:'(02) 8886-6761'} as StoreBranchModel,
        {type:'NCR', name:'MEGAMALL',address:'L G/F Building B SM Mega Mall Edsa, Cor Doña Julia Vargas Ave, Ortigas Center, Mandaluyong',contact:'(02)8656-4876'} as StoreBranchModel,
        {type:'NCR', name:'MPLACE RESIDENCES',address:' M Place@South Triangle, Panay Ave, Diliman, Quezon City',contact:'(02) 8277-5956'} as StoreBranchModel,
        {type:'NCR', name:'MUNTINLUPA',address:'G/F SM Supercenter Muntinlupa, National Rd, Bgy. Tunasan, Muntinlupa City',contact:'(02) 8659-1602'} as StoreBranchModel,
        {type:'NCR', name:'NORTH EDSA',address:'SM City North EDSA Annex 1 Tunnel, Bago Bantay, Quezon City ',contact:'(02) 8441-1451'} as StoreBranchModel,
        {type:'NCR', name:'NOVALICHES',address:' G/F SM City Novaliches, Quirino Hwy, Brgy. San Bartolome, Novaliches, Quezon City',contact:'(02) 8442-6179'} as StoreBranchModel,
        {type:'NCR', name:'PARANAQUE',address:'3/F SM City BF Parañaque, Dr. Arcadio Santos Ave,, Teoville East & West Subdivision, BF Homes, Parañaque',contact:'0917-824-5754'} as StoreBranchModel,
        {type:'NCR', name:'PASIG',address:'G/F SM Supercenter Pasig, Frontera Verde, Bgy. Ugong, C5, Ortigas, Pasig',contact:'(02) 8635-3436'} as StoreBranchModel,
        {type:'NCR', name:'PODIUM',address:'ADB AVE., Ortigas Center, Mandaluyong City',contact:''} as StoreBranchModel,
        {type:'NCR', name:'SAN LAZARO',address:' 2/F SM City San Lazaro, Felix Huertas cor A.H. Lacson Sta. Cruz, Manila',contact:'(02) 8740-7107'} as StoreBranchModel,
        {type:'NCR', name:'SANGANDAAN',address:' 2/F SM Center Sangandaan, Samson Road corner M.H. Del Pilar,, Barangay 3, Caloocan City, Caloocan',contact:'(02) 8277-6042'} as StoreBranchModel,
        {type:'NCR', name:'SHOPKING DON ANTONIO',address:'Bldg Lot 7&8, Unit L2 Lower Ground Level, Shopking Isidora Hills, Blk. 7 Holy Spirit Dr, Quezon City',contact:'(02) 8952-7784'} as StoreBranchModel,
        {type:'NCR', name:'SM CITY EAST ORTIGAS ',address:'2/F SM City East Ortigas, Ortigas Avenue Extension, Brgy. Sta. Lucia, Pasig City',contact:'(02) 8631-9349'} as StoreBranchModel,
        {type:'NCR', name:'SM MAKATI',address:' G/F SM Hypermarket Makati South Super Highway cor. Finlandia St., Bgy. San Isidro PH, Makati',contact:'(02) 8889-4841'} as StoreBranchModel,
        {type:'NCR', name:'SOUTHMALL',address:'2/F SM Southmall East Wing, Alabang-Zapote Road,, Pilar Village, Almanza Uno, Las Piñas, Las Pinas',contact:'(02) 8806-7444'} as StoreBranchModel,
        {type:'NCR', name:'STA.MESA',address:'L/GF SM City Sta. Mesa, Aurora Blvd., Dona Imelda Ave., Quezon City, Quezon City',contact:'(02) 8715-4819'} as StoreBranchModel,
        {type:'NCR', name:'SUCAT',address:'G/F SM City Sucat, Dr. A. Santos Ave., Bgy. San Dionisio, Sucat, Parañaque',contact:'(02) 8829-7625'} as StoreBranchModel,
        {type:'NCR', name:'VALENZUELA',address:'2/F SM City Valenzuela, MacArthur Highway, Brgy, Valenzuela',contact:'(02) 8292-7336'} as StoreBranchModel,
        
        {type:'VISAYAS', name: 'BACOLOD	', address:'	G/F Sm City Bacolod Bldg. A, Poblacion Reclamation Area, Bacolod City	', contact:'	(034) 468-0135'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL BORACAY	', address:'	Ground floor Citymall Boracay Sitio Diniwid, Boracay Island, Malay, 5600 Aklan	', contact:'	0917-829-3024'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL DANAO	', address:'	Extension Cor, Citymall Danao, Olivar Sr, F. Ralota St, Danao City, 6004 Cebu	', contact:'	0917-627-5430'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL DUMAGUETE	', address:'	Citymall Dumaguete, Veterans Avenue, National Highway, Dumaguete	', contact:'	0917-621-6795'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL GOLDENFIELDS	', address:'	Goldenfields Commercial Complex, Araneta Ave, Brgy. Singcang, Bacolod, Negros Occidental	', contact:'	0917-816-1832'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL JARO	', address:'	G/F CityMall Tagbak Jaro, McArthur Hway, Barangay Tagbak, Jaro, IloIlo City	', contact:'	0917-671-2006'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL KABANKALAN	', address:'	 Barangay, Ground floor Citymall, Justice Perez Highway, Kabankalan	', contact:'	0917-622-0216'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL KALIBO	', address:'	G/F CityMall Kalibo Aklan, Quimpo St., Connecting Mabini and Toting Reyes St., Brgy. Andagao, Kalibo, Malay	', contact:'	0917-671-3737'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL MANDALAGAN BACOLOD	', address:'	Lacson Street corner G.M, Cordova Ave.,Baranggay Mandalagan, Bacolod City	', contact:'	0917-621-6161'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL PASSI	', address:'	Ground Floor City Mall, Simeon Aguilar St, Passi City, 5037 Iloilo	', contact:'	0917-817-5004'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL PAVIA	', address:'	Citymall Pavia, Old Iloilo - Capiz Rd, Pavia	', contact:'	0917-807-8456'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL SAN CARLOS	', address:'	Ground floor Citymall San Carlos Azcona St. cor. C.L. Ledesma Ave.,, Barangay II, San Carlos City, 6127 Negros Occidental	', contact:'	0917-625-8803'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CITY MALL VICTORIAS	', address:'	Ground floor CityMall, Osmeña Ave, Brgy, Victorias City	', contact:'	(034) 702-0617'} as StoreBranchModel,
        {type:'VISAYAS', name: 'DELGADO MALL	', address:'	G/F SM City Delgado Annex Cor. Minor St. & Valeria St., Delgado, Iloilo City	', contact:'	(033) 335-8121'} as StoreBranchModel,
        {type:'VISAYAS', name: 'GAISANO CAPITAL REAL TAC LEYTE	', address:'	78 Real St, Downtown, Tacloban City, Leyte	', contact:'	'} as StoreBranchModel,
        {type:'VISAYAS', name: 'J CENTER MALL CEBU	', address:'	U/GF Jmall Centre, AS Fortunata St, V.Albano, Extension, Mandaue City	', contact:'	(032) 520-3224'} as StoreBranchModel,
        {type:'VISAYAS', name: 'ILOILO	', address:'	 L/GF Northwing SM City, Mandurriao, Iloilo City	', contact:'	(033) 320-7667'} as StoreBranchModel,
        {type:'VISAYAS', name: 'ISLAND CENTRAL MALL MACTAN	', address:'	 2nd Floor (Units 33-39), Mactan Economic Zone 1,, M.L. Quezon National Highway, Bgy. Pusok, Lapu-Lapu City	', contact:'	(032) 260-1719'} as StoreBranchModel,
        {type:'VISAYAS', name: 'CONSOLACION	', address:'	2/F SM City Consolacion, Cebu North Road,, Brgy. Lamac, Municipality of Consolacion, Cebu	', contact:'	(032) 260-0063'} as StoreBranchModel,
        {type:'VISAYAS', name: 'NORTH POINT BACOLOD	', address:'	Ground Floor, The District Ayala North Point Barangay Zone 15, Talisay City	', contact:'	(034) 432-9125'} as StoreBranchModel,
        {type:'VISAYAS', name: 'SM CENTER ORMOC	', address:'	Real St, Ormoc, 6541 Leyte	', contact:'	0919-086-8199'} as StoreBranchModel,
        {type:'VISAYAS', name: 'SM CITY-CEBU	', address:'	 U/GF SM City Cebu, Cebu City, 6000 Cebu	', contact:'	0917-892-2348'} as StoreBranchModel,
        {type:'VISAYAS', name: 'SM SAVEMORE MARKET TACLOBAN	', address:'	3/F SM Savemore Market Tacloban, Justice Romualdez St. Barangay 13, Tacloban City	', contact:'	(053) 832-2045'} as StoreBranchModel,
        {type:'VISAYAS', name: 'SM SEASIDE CITY CEBU 	', address:'	 G/F SM City Seaside Cebu, South Rd., Properties,Cebu, Cebu City	', contact:'	(02) 8367-7253'} as StoreBranchModel,

        {type:'MINDANAO', name: 'CAGAYAN DE ORO	', address:'	Second Floor, SM PH, Upper Carmen, Cagayan de Oro	', contact:'	0917-6713691'} as StoreBranchModel,
        {type:'MINDANAO', name: 'CITY MALL DIPOLOG	', address:'	CityMall, Dipolog City, Zamboanga del Norte	', contact:'	'} as StoreBranchModel,
        {type:'MINDANAO', name: 'CITY MALL KORONADAL	', address:'	Lacson St, City, Koronadal City, 9506 South Cotabato	', contact:'	(083) 520-2469'} as StoreBranchModel,
        {type:'MINDANAO', name: 'CITY MALL TAGUM	', address:'	CityMall Tagum, Maharlika Hi-way cor. Lapu-Lapu Ext., Magugpo Poblacion, Tagum, 8100 Davao del Norte	', contact:'	0917-819-5969'} as StoreBranchModel,
        {type:'MINDANAO', name: 'CITY MALL TETUAN	', address:'	G/F CityMall PH, Tetuan, Don Alfaro St, Barangay, Zamboanga	', contact:'	(062) 955-8399'} as StoreBranchModel,
        {type:'MINDANAO', name: 'DAVAO	', address:'	2/F SM City Davao, Quimpo Blvd cor. Tulip and Ecoland Drive,, Ecoland Subd., Matina, Davao City	', contact:'	(082) 297-7185'} as StoreBranchModel,
        {type:'MINDANAO', name: 'DS CDO DOWNTOWN PREMIER	', address:'	hird Floor, SM City CDO Downtown Premier, CM Recto corner Osmeña Street Cagayan de Oro City 9000 PH, Cagayan de Oro	', contact:'	0917-628-2853'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GAISANO CAPITAL LUNA SURIGAO	', address:'	Upper Ground Floor Gaisano Mall, Ground Floor, Gaisano Capital Zamboanga del Sur PH, San Pedro, Zamboanga, Rizal Ave, Pagadian City,	', contact:'	0922-417-7275'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GAISANO CAPITAL OZAMIZ	', address:'	Rizal Avenue corner 15 De Noviembre Sts, Ozamiz City, 7200 Misamis Occidental	', contact:'	0919-087-1955'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GAISANO CAPITAL PAGADIAN	', address:'	Upper Ground Floor Gaisano Mall, Ground Floor, Gaisano Capital Zamboanga del Sur PH, San Pedro, Zamboanga, Rizal Ave, Pagadian City	', contact:'	0922-417-7275'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GAISANO CAPITAL SAN FRANCISCO	', address:'	 G/F Gaisano Capital Agusan del Sur PH, Barangay 4, San Francisco	', contact:'	(085) 839-5803'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GAISANO TORIL	', address:'	Gaisano Grand Mall, Toril, Davao City, Davao del Sur	', contact:'	0919-087-1956'} as StoreBranchModel,
        {type:'MINDANAO', name: 'GENERAL SANTOS	', address:'	2/F SM City General Santos, Santiago Blvd. cor., San Miguel St., General Santos City	', contact:'	(083) 878-0565'} as StoreBranchModel,
        {type:'MINDANAO', name: 'LANANG	', address:'	3/F SM Lanang Premier Mall, J.P. Laurel Ave., Brgy. San Antonio, Agdao District,, Davao City	', contact:'	(082) 285-1644'} as StoreBranchModel,
        {type:'MINDANAO', name: 'NCCC MALL BUHANGIN	', address:'	NCCC Buhangin, Mandug Rd, Brgy. Buhangin, Davao City, 8000 Davao del Sur	', contact:'	'} as StoreBranchModel,
        {type:'MINDANAO', name: 'SM CDO DOWNTOWN PREMIER 	', address:'	3rd Flr, SM City CDO Downtown Premier, CM Recto corner Osmeña Street Cagayan de Oro City	', contact:'	0917-628-2853'} as StoreBranchModel,
        {type:'MINDANAO', name: 'SMC KAUSWAGAN	', address:'	G/F Savemore Market Kauswagan, Iligan Highway cor. Pelaez St., Kauswagan, Cagayan de Oro City	', contact:'	(088) 880-1955'} as StoreBranchModel,
       ]},
      { title: 'ALL HOME', src: 'assets/stores/All-Home.png', branches: [
        {name: 'AGRO', address: 'TENANT 3 STAR PLAZA AGRO NATIONAL ROAD BRGY. PUTUTAN MUNTINLUPA CITY', contact: '‎(02) 8232996 / ‎09183438981 / ‎09167334837/ 09065695684', active: 0} as StoreBranchModel,
        {name: 'ALL BUILDERS DASMA', address: 'AllBuilders, Molino-Paliparan Road, Barangay Salawag, Dasmarinas City, Cavite', contact: '09295028306 / 09163755758', active: 0} as StoreBranchModel,
        {name: 'ALABANG', address: '3rd LEVEL STAR MALL ALABANG, MUNTINLUPA CITY', contact: '‎(02) 880 1115 / ‎09560899676', active: 0} as StoreBranchModel,
        {name: 'ANTIPOLO', address: 'GROUND FLOOR ALLHOME ANTIPOLO, MANUEL L. QUEZON EXIT. BRGY. SAN ROQUE ANTIPOLO RIZAL', contact: '(02) ‎5324663 / 09770041677 / 09271651285', active: 0} as StoreBranchModel,
        {name: 'BACOOR', address: 'MB Villar Ave., Brgy. Molino III, Bacoor, Cavite', contact: '09562806882 / 09476158792', active: 0} as StoreBranchModel,
        {name: 'BATAAN', address: 'GROUND FLOOR VISTAMALL BATAAN, ROMAN HI-WAY BRGY. CUPANG BALANGA BATAAN', contact: '(047) 6334692 / ‎09335727337 / ‎09955834461 / ‎09323270092', active: 0} as StoreBranchModel,
        {name: 'BULACAN', address: 'LGF-02 STAR MALL BULACAN NATIONAL HIGHWAY, KAYPIAN ROAD CITY OF SAN JOSE DEL MONTE BULACAN', contact: '(044) 7691641 / ‎09328698307/ 09206895465', active: 0} as StoreBranchModel,
        {name: 'BUTUAN', address: 'Agusan – Misamis Oriental Rd. KM 6 National Highway Brgy. Ampayon, Butuan City, Agusan Del Norte', contact: '09471790512 / 09260632157', active: 0} as StoreBranchModel,
        {name: 'CDO', address: 'ROSARIO CRESENT ST. LIMKETKAI CENTER CAGAYAN DE ORO, MISAMIS ORIENTAL', contact: '09455947546 / 09288389820/ 09291967760', active: 0} as StoreBranchModel,
        {name: 'CEBU', address: '2ND FLOOR, STARMALL AZIENDA SEAVIEW SUBD. LAWAAN TALISAY CITY, CEBU', contact: '(032) 3406473 / ‎(032) 3406476/ 09231392975', active: 0} as StoreBranchModel,
        {name: 'DAANGHARI', address: 'VISTA MALL DAANGHARI, COR. DAANGHARI RD. MOLINO, BACOOR, CAVITE', contact: '‎(046) 4354801 / 09278787854 / ‎09999823443/ 09060111941', active: 0} as StoreBranchModel,
        {name: 'DASMA', address: 'Aguinaldo Hiway Barangay San Agustin 2, Dasmariñas, Cavite', contact: '0961-297-2515/0915-047-3438', active: 0} as StoreBranchModel,
        {name: 'EVIA', address: 'Daang Hari Rd., Las Piñas', contact: '09453011932 / 0928650 8627', active: 0} as StoreBranchModel,
        {name: 'GAPAN', address: 'KM 88 Maharlika Highway Brgy. Sto. Cristo Sur, Gapan, Nueva Ecija', contact: '0908-349-5604 / 0906-349-3565', active: 0} as StoreBranchModel,
        {name: 'GEN TRIAS', address: 'All Home Vista Mall General Trias, Arnaldo Highway brgy San Francisco General Trias Cavite 4107', contact: '09266466459 / 09475946984 / 09456958535', active: 0} as StoreBranchModel,
        {name: 'GLOBAL SOUTH', address: 'C5 EXTENSION RD., BRGY. PULANG LUPA UNO LAS PINAS CITY', contact: '09081387625 / 09959264323/ 09150726972 / 09422927719', active: 0} as StoreBranchModel,
        {name: 'ILOILO', address: 'VISTA MALL ILOILO,CIRCUMFERENTIAL ROAD 1,BRGY PULO MAESTRA VITA,OTON, ILOILO CITY', contact: '09458320837 / 09999288163 / 09996586986', active: 0} as StoreBranchModel,
        {name: 'IMUS', address: 'PALICO 4 AGUINALDO HIGHWAY IMUS CAVITE ', contact: '0966 169 1766', active: 0} as StoreBranchModel,
        {name: 'KAWIT', address: 'VISTA MALL KAWIT CENTENNIAL RD. BRGY MAGDALO KAWIT CAVITE', contact: '(046)4239751 / 09216863388 / 09054551712', active: 0} as StoreBranchModel,
        {name: 'KORONADAL', address: 'Carpenter Hill, Gensan Drive, Koronadal City, South Cotobato', contact: '09273625218 / 09395688095', active: 0} as StoreBranchModel,
        {name: 'LAS PINAS', address: 'GRD FLR VISTA MALL LAS PINAS, PAMPLONA LAS PINAS CITY', contact: '(0999) 462 9036 / (0915) 072 6972', active: 0} as StoreBranchModel,
        {name: 'LIBIS', address: 'E. RODRIGUEZ JR. AVE. BRGY. BAGUMBAYAN, QUEZON CITY', contact: '09255115050/ 09770631263', active: 0} as StoreBranchModel,
        {name: 'MALOLOS', address: 'McArthur Highway, Brgy. Longos, Malolos City, Bulacan', contact: '09758491928 / 09433206814/ 09323270092', active: 0} as StoreBranchModel,
        {name: 'NAGA', address: 'MAHARLIKA HI-WAYB BRGY. DEL ROSARIO NAGA CITY', contact: '09455995831 / 09234395798 / 09398845154', active: 0} as StoreBranchModel,
        {name: 'NORTH MOLINO', address: 'North Molino Blvd. Barangay San Nicolas I City of Bacoor Cavite', contact: '0999-573-2284/0905-573-0754', active: 0} as StoreBranchModel,
        {name: 'PAMPANGA', address: 'CAMELLA ANDALUSIA, BRGY. SAN AGUSTIN MC ARTHUR HI-WAY SAN FERNANDO PAMPANGA', contact: '‎09065644029 / ‎09212827689/ 09420488601', active: 0} as StoreBranchModel,
        {name: 'SAN ILDEFONSO', address: 'Maharlika Highway, Brgy. Garlang, San Ildefonso, Bulacan', contact: '09673658180 / 09297200976', active: 0} as StoreBranchModel,
        {name: 'SHAW', address: 'Ground Floor Starmall Edsa Cor. Shaw Blvd. Wack Wack Mandaluyong City', contact: '09950177784 / ‎09325118484 / 09238129593', active: 0} as StoreBranchModel,
        {name: 'STA ROSA', address: 'GROUND FLR VISTAMALL STA ROSA TAGAYTAY ROAD STA ROSA LAGUNA', contact: '‎09278920361 / ‎09326689999/ 09178847036', active: 0} as StoreBranchModel,
        {name: 'TAGUIG', address: 'GROUND FLR. VISTAMALL TAGUIG LEVI MARIANO AVE, BRGY USUSAN TAGUIG CITY', contact: '(02) 6318981 / ‎09204361109 / ‎09065695684‎/ 09065695684 / 09322178997', active: 0} as StoreBranchModel,
        {name: 'TANZA', address: 'VISTA MALL TANZA BGY. PUNTA 2 TANZA- TRECE ROAD TANZA CAVITE 4108', contact: '09297792493 / 09162624085', active: 0} as StoreBranchModel,
        {name: 'WIL TOWER', address: 'WIL TOWER, VISTA PLACE, EUGENIO LOPEZ DRIVE, BARANGAY SOUTH TRIANGLE, QUEZON CITY', contact: '09196286557 / 09255071580 / 09273045454', active: 0} as StoreBranchModel
      ]},
      { title: 'CW HOME DEPOT', src: 'assets/stores/CW.png', branches: [
        {name: 'ALABANG', address: 'LOT 103-117 ALABANG- ZAPOTE ROAD COR. FILINVEST AVE., WESTGATE ALABANG, MUNTINLUPA CITY', contact: '(02) 8771-1625', active: 0} as StoreBranchModel,
        {name: 'BALINTAWAK', address: '#1240 EDSA, BRGY. APOLONIO SAMSON, QUEZON CITY', contact: '(02) 8332-2598', active: 0} as StoreBranchModel,
        {name: 'COMMONWEALTH', address: 'COMMONWEALTH AVE., MATANDANG BALARA, QUEZON CITY', contact: '(02) 8351-8971', active: 0} as StoreBranchModel,
        {name: 'IMUS', address: 'AGUINALDO HIGHWAY, NEAR CORNER DAANG HARI, BRGY. ANABU II-D, IMUS CAVITE', contact: '(046) 472-7673', active: 0} as StoreBranchModel,
        {name: 'ORTIGAS', address: 'DOÑA JULIA VARGAS AVE., PASIG CITY', contact: '(02) 8683-0823', active: 0} as StoreBranchModel,
        {name: 'PAMPANGA', address: 'OLONGAPO-GAPAN ROAD, BRGY. SAN JOSE, CITY OF SAN FERNADO', contact: '(045) 455-1859', active: 0} as StoreBranchModel,
        {name: 'STA. ROSA', address: 'BRGY. PULONG STA. CRUZ, STA. ROSA TAGAYTAY ROAD, CITY OF STA. ROSA, LAGUNA', contact: '(049) 544-0700', active: 0} as StoreBranchModel
      ]},
      { title: 'FEDERAL HARDWARE', src: 'assets/stores/Federal.png', branches: [
        {name: 'BIÑAN', address: 'BARRIO TUBIGAN, BIÑAN CITY, LAGUNA', contact:	'(049) 520-6704', active: 0} as StoreBranchModel,
        {name: 'CAINTA', address: '9 IMELDA AVENUE, CAINTA, FELIX AVE., CAINTA, RIZAL', contact:	'(02) 8656-5377', active: 0} as StoreBranchModel,
        {name: 'CUBAO', address: '985 AURORA BLVD., PROJECT 3, QUEZON CITY', contact:	'(02) 3434-2779', active: 0} as StoreBranchModel,
        {name: 'TAYTAY', address: 'MANILA EAST ROAD, TAYTAY RIZAL', contact:	'(02) 8284-2206', active: 0} as StoreBranchModel
      ]},
      { title: 'HANDYMAN', src: 'assets/stores/Handyman.png', branches: [
        {name: 'ALIMALL', address: 'Lower Ground Floor Alimall Cubao , Cubao Quezon City', contact: '709-2071', active: 0} as StoreBranchModel,
        {name: 'AYALA ARVO MARIKINA', address: 'Ground Floor Ayala Malls Marikina, Liwasang Kalayaan, Marikina Heights, Marikina City', contact: '0999-229-2456', active: 0} as StoreBranchModel,
        {name: 'AYALA FELIZ ', address: '4th Level, Ayala Feliz, Marcos Highway, Cor E. Roriguez Ave. Brgy. Dela Paz, Pasig City', contact: '09988465600', active: 0} as StoreBranchModel,
        {name: 'AYALA MALLS CIRCUIT', address: 'level 3 Ayala Malls Circuit, Circuit Makati , Hippodromo St., Brgy  Carmona  Makati City.', contact: '09988465563 ', active: 0} as StoreBranchModel,
        {name: 'AYALA SOUTH PARK', address: 'Ground Floor South Park-Ayala Mall Alabang, Muntinlipa City', contact: '851-5290/ 851-5289', active: 0} as StoreBranchModel,
        {name: 'BALAGTAS', address: 'Ground Floor Balagtas Town Center, McArthur Highway Borol 1st, Balagtas, Bulacan', contact: '(044) 693-2567', active: 0} as StoreBranchModel,
        {name: 'CHERRY SHAW', address: 'Upper Ground Flr, Cherry Shaw Boulevard, Mandaluyong City', contact: '531-9870/ 532-3940', active: 0} as StoreBranchModel,
        {name: 'CITI SQUARE MALABON', address: 'City Square Malabon C4 Road, Dagat Dagatan, Malabon Metro Manila', contact: '287-79-29', active: 0} as StoreBranchModel,
        {name: 'FARMERS', address: '3rd flr. New Farmers Plaza, Araneta Center, Quezon City', contact: '421-0507', active: 0} as StoreBranchModel,
        {name: 'FILINVEST', address: '3rd Level Left Toll Wing Festival Supermall Alabang Muntinlupa City', contact: '772-2475/807-8870', active: 0} as StoreBranchModel,
        {name: 'GALLERIA SOUTH LAGUNA', address: '3rd Level, Galleria South San Pedro Laguna', contact: 'N/A', active: 0} as StoreBranchModel,
        {name: 'HAPPY GO', address: '2nd Floor Ibaba St., Brgy. Bignay, Valenzuela City', contact: '0936-444-7195', active: 0} as StoreBranchModel,
        {name: 'IL CENTRO CAINTA', address: '2nd Floor. IL Centro Sta. Lucia Mall Marcos Hiway cor. Felix Ave. Cainta Rizal', contact: '632-7951-52', active: 0} as StoreBranchModel,
        {name: 'METRO PLAZA MALL', address: 'Upper Ground Flr. Metro Plaza Mall Malaria Road, Quirino Highway Caloocan City', contact: '09988465572', active: 0} as StoreBranchModel,
        {name: 'MEYCAUAYAN', address: 'Robinsons Townville Camalig, Meycauayan Bulacan.', contact: '(044) 769-4060', active: 0} as StoreBranchModel,
        {name: 'MONTALBAN2', address: 'Montalban Town Center2 San Jose Rodriguez, Rizal', contact: '941-5627', active: 0} as StoreBranchModel,
        {name: 'NEPO MALL ANGELES', address: '3rd Floor Nepomall, Teresa Avenue cor. St. Joseph St., Angeles City', contact: '02-246-8402/045-409-0154', active: 0} as StoreBranchModel,
        {name: 'ONE MALL VALENZUELA', address: '2nd Level, 6008 Gen. T. De Leon Road Brgy. Gen. T. De Leon Valenzuela City', contact: '939-0826/ 372-7420', active: 0} as StoreBranchModel,
        {name: 'PULILAN', address: 'Doña Remedios Trinidad Highway, Pulilan Junction, Barangay Cut-Cot, Pulilan, Bulacan', contact: '(632) 299-8354', active: 0} as StoreBranchModel,
        {name: 'RIVERBANKS', address: '1st Level, Riverbanks Center84 A. Bonifacio Avenue, Barangka, Marikina City', contact: '369-5079/ 942-6430', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-ANGELES', address: '3rd Flr. Robinsons Place Balibago, McArthur Highway, Angeles City', contact: '246-8306/(6345) 892-2618', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-ANTIPOLO', address: '2nd Flr. Robinsons Place Antipolo, sumulong Highway Circumference Ave., brgy Dela Paz Antipolo City.', contact: '531-5460', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-DASMARIÑAS', address: 'Robinsons Place Dasmariñas E. Aguinaldo Highway cor. Governor Drive Pala-Pala, Dasmariñas, Cavite', contact: '852-2001', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-ERMITA', address: '3rd Level, Robinsons Place Ermita, M. Adriatico St., Malate Manila', contact: '528-0852 / 397-70-36', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-LAS PIÑAS', address: '2nd Floor, Robinsons Place Las Piñas, 345  Alabang- Zapote Road, Brgy. Talon Uno las Pinas City', contact: '856-4163', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-MALOLOS BULACAN', address: '3rd Level Robinsons Place, McArthur Highway, Brgy. Mabolo, Malolos Bulacan', contact: '(044) 794-0727', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-NOVALICHES', address: 'Ground Flr Robinsons Place, beside Big R, Quirino High-way, Brgy. Maligaya Novaliches', contact: '935-1866', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-OTIS', address: 'Robinsons Place Manila Gas, 2nd Floor Paz Guanzon St., Paco Manila', contact: '559-0703/559-0670', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-PALAWAN', address: '2nd Level Robinsons Place, National Highway, Brgy. San Miguel, Puerto Prinsesa Palawan', contact: '(048) 433-0097', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-PAMPANGA', address: 'Ground Floor Robinsons Place, Starmills, Brgy. San Jose City of San Fernando Pampanga', contact: '636-3537/875-2102/246-7051', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-PIONEER', address: 'Robinsons Place Pioneer, Edsa cor. Pioneer St., Mandaluyong City', contact: '398-8020 to 21', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS PLACE-TAGAYTAY', address: 'Ground Floor, Robinsons Place Tagaytay, E. Aguinaldo Highway, Brgy. Maharlika Tagaytay City.', contact: '(046) 4137749', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS-CAINTA', address: '2nd Level RHI Big Supercenter Cainta Junction, Ortigas Ave., Ext.Brgy. Sto. Domingo, Cainta Rizal', contact: '240-4273', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS-GALLERIA', address: '1st Level Robinsons Galleria Ortigas Ave. Quezon City', contact: '633-6650/ 633-6627', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS-MALABON ', address: '2L Robinsons Town Mall Malabon, Gov. Pascual Ave. cor. Crispin St., Tinajeros Malabon City', contact: '294-1393', active: 0} as StoreBranchModel,
        {name: 'ROBINSONS-METRO EAST', address: '3rd Flr. Handyman Robinsons Metroeast, Marcos Hi-Way, Dela Paz, Pasig City', contact: '668-1935', active: 0} as StoreBranchModel,
        {name: 'SHAW CENTER MALL', address: '3rd level Shaw Center Mall, Shaw Blvd. cor Nueve De Pebrero, Mandaluyong City', contact: '641-5818/ 641-5832', active: 0} as StoreBranchModel,
        {name: 'SILANG CAVITE', address: 'Ground Flr.Premier Plaza Mall, Emilio Aguinaldo Highway cor. J. Rizal Road Silang Cavite', contact: '046-460-4069', active: 0} as StoreBranchModel,
        {name: 'TRINOMA', address: '2nd Flr. Space#2083 North Depot Comm\'l Center Brgy. Pag-asa, Quezon city', contact: '901-3676 / 901-3677', active: 0} as StoreBranchModel,
        {name: 'WALTERMART - BICUTAN', address: '2nd Floor Waltermart Mall Bicutan, East Service Road, San Martin de Porres, Parañaque City', contact: '828-8552', active: 0} as StoreBranchModel,
        {name: 'WALTERMART - GUIGUINTO', address: 'Ground Flr. Waltermart Mall, McArthur Highway, Ilang-Ilang, Guiguinto Bulacan', contact: '(044) 794-3437', active: 0} as StoreBranchModel,
        {name: 'WALTERMART - SAN FERNANDO', address: '1st Level of Waltermart, McArthur Hi-Way, Brgy. San Agustin, San Fernando City, Pampanga', contact: '(045) 435-0485/435-3968', active: 0} as StoreBranchModel,
        {name: 'WALTERMART - STA. MARIA', address: '2nd Floor Waltermart Center, Sta. Maria Provincial Road, cor. By Pass Road, Brgy. Sta. Clara,  Sta.Maria Bulacan.', contact: '(044) 641-1089', active: 0} as StoreBranchModel,
        {name: 'WALTERMART - TRECE MARTIRES', address: '2nd Floor, Waltermart Governors Drive Trece Martires City, Cavite', contact: '(046)4604013', active: 0} as StoreBranchModel,
        {name: 'WHI DASMARIÑAS', address: 'Waltermart Mall #30 Aguinaldo Hi-Way Burol, Dasmariñas Cavite', contact: '(046) 416 2398', active: 0} as StoreBranchModel,
        {name: 'WHI MAKATI', address: '4th Floor. WHI Mall, 790 Chino Roces cor. A. Arnaiz Ave., Makati City', contact: '889-7889', active: 0} as StoreBranchModel,
        {name: 'WHI NORTH EDSA', address: '2nd Flr. Waltermart Mall Center Bldg., Dangay St. Veterans Village Quezon City', contact: '332-1167-68', active: 0} as StoreBranchModel,
        {name: 'WHI PLARIDEL', address: 'Unit 2-7 2nd Floor Waltermart Plaridel, Cagayan Valley Road, Banga First Plaridel, Bulacan Pampanga', contact: '0998-8465624', active: 0} as StoreBranchModel,
        {name: 'XENTRO MALL ANTIPOLO', address: 'Ground Floor Xentro Mall Sumulong Highway, Brgy. Mambugan, Antipolo City.', contact: '09988465587', active: 0} as StoreBranchModel
      ]},
      { title: 'TRUE VALUE', src: 'assets/stores/True-Value.png', branches: [
        {name: 'ABREEZA', address: '2nd Level Abreeza Mall, Bajada Davao City', contact: '(082) 321 1736', active: 0} as StoreBranchModel,
        {name: 'AYALA CENTER CEBU', address: '318B 3rd Floor Ayala Center Cebu, Cebu Business Park, Cebu City', contact: '266 1522', active: 0} as StoreBranchModel,
        {name: 'AYALA FAIRVIEW TERRACES', address: 'GF Fairview Terraces, Cor. Maligaya Park Novaliches, Quezon City', contact: '(02) 961 1569', active: 0} as StoreBranchModel,
        {name: 'AYALA MALLS THE 30TH', address: '3rd Level Ayala Malls the 30th Meralco Ave, Pasig City', contact: '(02) 636 2878', active: 0} as StoreBranchModel,
        {name: 'AYALA MALLS CLOVERLEAF', address: '3rd Level Ayala Malls Cloverleaf, Balintawak, Quezon City', contact: '', active: 0} as StoreBranchModel,
        {name: 'CENTRIO', address: '3rd Level Ayala Centrio Mall, Claro M. Recto Cor. Corales Ave. Cor Capt. Roa St., Cagayan De Oro City', contact: '(088) 323 1418', active: 0} as StoreBranchModel,
        {name: 'CENTURY', address: 'Century Plaza Mall Lower Ground, Makati City', contact: '(02) 893 8569', active: 0} as StoreBranchModel,
        {name: 'ESTANCIA', address: 'Estancia Capitol Common Lower Floor Meralco Ave. Cor. Shaw Blvd. Brgy. Oranbo, Pasig City', contact: '(02) 531 9693', active: 0} as StoreBranchModel,
        {name: 'MARQUEE', address: '2nd Floor Marquee Mall, Francisco G. Nepo Ave., Pulung Maragul, Angeles City, Pampanga', contact: '(045) 304 0949', active: 0} as StoreBranchModel,
        {name: 'MAXILOM GALLERIA CEBU', address: '2nd Floor Robinsons Galleria Cebu Brgy. Tejero General Maxilom Ave., Cebu City', contact: '(032) 230 7665', active: 0} as StoreBranchModel,
        {name: 'SANTOLAN TOWN PLAZA', address: '2nd Floor, Santolan Town Plaza, Santolan Road Street, Little Baguio, San Juan City', contact: '', active: 0} as StoreBranchModel,
        {name: 'SHANGRI-LA', address: '6F Shangri-la Plaza Mall EDSA cor Shaw Blvd., Mandaluyong City', contact: '(02) 635 0410', active: 0} as StoreBranchModel,
        {name: 'TV CAPITOL CENTRAL BACOLOD', address: '2nd level Ayala Malls Capitol Central, Gatuslao St., Corner N.Road, Bacolod City 6100', contact: '', active: 0} as StoreBranchModel,
        {name: 'UPTOWN BGC', address: 'Lower Ground Floor, Unit B108 Uptown Place Mall, 36th Street cor 9th Avenue, Uptown Bonifacio Brgy. Fort, Taguig City', contact: '(02) 869 5935', active: 0} as StoreBranchModel,
      ]},
      { title: 'WILCON', src: 'assets/stores/Wilcon.png', branches: [
        {type: 'LUZON', name: 'Alabang', address: '#8003 Real St. Alabang Zapote Road, Almanza uno Las Piñas', contact: ' (02) 8772-0312', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Antipolo', address: 'Marcos Hi-way, Mayamot, Antipolo City', contact: '(02) 8477-5868 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Balintawak', address: '#1274 EDSA Balintawak, Quezon City ', contact: '  (02) 8362-8273 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Baliuag', address: 'Km. 48 DRT Highway, Brgy. Tarcan, Baliuag, Bulacan', contact: '(044) 766-1781', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Batangas', address: 'Diversion Road, Brgy. Alangilan, Batangas City', contact: '(043) 722-0608 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Cabanatuan', address: 'LOT 2040-C-3-B & Lot 2040-C-4 Sumacab Este, Cabanatuan City', contact: '(044) 803-9254', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Calamba', address: 'National Road, Brgy. Halang, Calamba City, Laguna', contact: '(049) 545-1817', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Daraga Alabay', address: 'Peñafrancia, Daraga, Albay', contact: '(Globe) 0917-8738525', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Dasmarinas', address: 'Governor\'s Drive, Brgy. Paliparan, Dasmariñas City, Cavite', contact: '(046) 481-9977 to 79', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Dau', address: 'Mc. Arthur Highway Brgy. Dau Mabalacat, Pampanga', contact: '(045) 624-1118 to 1123', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Fairview', address: '#16 Commonwealth Ave., Brgy. Commonwealth, Quezon City', contact: '(02) 3428-6246 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Filinvest', address: 'B29 Alabang Zapote Rd., cor. Bridgeway Ave., Filinvest Corporate City, Muntinlupa City', contact: '(02) 8772-6178', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'General Trias', address: 'Lot 2680-F-4, Sitio Defuego, Brgy. San Francisco, General Trias, Cavite', contact: '(046) 409-3986', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'It hub', address: '#2251 Chino Roces Avenue, Brgy. Bangkal Makati City', contact: '(02) 8834-5002 to 5004 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Iguig Cagayan', address: 'Cagayan Valley Rd, Brgy. Bayo, Iguig Cagayan', contact: '(078) 375-1923', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Kawit', address: 'Centennial Road, Brgy. Magdalo Potol, Kawit, Cavite', contact: '(046) 431-7712', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Laoag', address: 'Airport Rd., Brgy. Buttong, Laoag City, Ilocos Norte', contact: '(077) 670-8639', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Libis', address: '#90 E. Rodriguez Jr. Ave., Ugong Norte Murphy, Libis, Quezon City', contact: ' (02) 8634-8387 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Lipa', address: 'Brgy. Bugtong Na Pulo, Lipa CIty, Batangas', contact: '(043) 756-0405', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Mexico', address: 'Gapan-Olongapo Road, Brgy. Lagundi, Mexico, Pampanga', contact: '(045) 966-0303', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Molino', address: 'Bacoor Blvd (formerly Molino Boulevard), Barangay Mambog IV, Bacoor City, Cavite', contact: '(046) 435-1497', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Naga', address: 'Brgy. Del Rosario, Naga City, Camarines Sur', contact: '(054) 881-2712', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Quirino', address: 'L119 C1 Mindanao Avenue, Brgy. Talipapa, Quezon Cit', contact: '(02) 3453-2229 / (02) 3453-5910 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Quezon Avenue', address: '#24 Quezon Ave. Doña Josefa, D4, Quezon City', contact: '(02) 8292-6255 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Palawan', address: 'Lot 5476-A, National Highway Cor. Golden Valley Road, Brgy. Sicsican, Puerto Princesa City Palawan', contact: '(048) 433-0703 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Pasong tamo', address: '#2212 Chino Roces Ave. San Lorenzo Makati City (beside Cityland Tower, infront of Don Bosco Chapel)', contact: '(02) 8280-6544 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'San Fernando', address: 'Freeway St., Olongapo-Gapan Rd., Brgy. Dolores, San Fernando City, Pampanga', contact: '(045) 961- 7602', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'San Isidro Antipolo', address: 'Lot 2-A, Barangay San Isidro, Antipolo City, Rizal', contact: '(02) 8288-5544', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'San Jose Del monte Bulacan', address: 'Quirino Highway, Barangay Tungkong Mangga, San Jose del Monte, Bulacan', contact: '(Globe) 0917-8738554', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'San Pablo', address: 'Doña Maria Village Phase 2, Brgy. Bagong Bayan, San Pablo City', contact: '(049) 503-4471', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Silang', address: 'Purok 9, Brgy. Lalaan II, Silang, Cavite', contact: '(046) 409-2558', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Sta. Rosa', address: 'Tagaytay Rd. Brgy Pulong, Sta. Cruz, Sta. Rosa , Laguna', contact: '(049) 544-7844', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Sto. Tomas Batangas', address: 'Barangay Sta. Anastacia, Sto. Tomas, Batangas', contact: '(043) 740-2984', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Sucat', address: 'Dr. A. Santos Ave., Brgy. San Dionisio, Sucat, Parañaque City', contact: '(02) 8820-4046', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Tarlac', address: 'Mc. Arthur H-way, Sta. Monica Village, San Rafael, Tarlac City', contact: '(045) 982-4388 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Tayabas', address: ' Brgy. Isabang, Tayabas, Quezon', contact: '(042) 710-1153 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Taytay', address: 'Manila East Road, Brgy. San Juan, Taytay Riza', contact: '(02) 8571-8374 ', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Valenzuela', address: '#292 McArthur Hi-way, Dalandanan, Valenzuela City', contact: '(02) 8292-6254', active: 0} as StoreBranchModel,
        {type: 'LUZON', name: 'Villasis', address: 'Barangay Bacag Villasis, Pangasinan', contact: '(075) 523-8678', active: 0} as StoreBranchModel,
        
        {type: 'HOME ESSENTIALS', name: 'Alimall', address: 'Lower Ground Floor Alimall, Araneta Center, Quezon City', contact: '(02) 3440-3039 / 8709-2717', active: 0} as StoreBranchModel,
        {type: 'HOME ESSENTIALS', name: 'City Center', address: 'Anchor 1 121 Visayas Ave., Brgy. Bahay Toro, Quezon City', contact: '(02) 8990-5876 / 8990-5874', active: 0} as StoreBranchModel,
        {type: 'HOME ESSENTIALS', name: 'Sta. Mesa', address: '#425 Piña Ave., Zone 057, Brgy. 585, Sampaloc, Manila', contact: '(02) 8713-1003 / 8713-0147 ', active: 0} as StoreBranchModel,

        {type: 'VISAYAS', name: 'Bacolod', address: 'Brgy. Matab-ang, Talisay City, Negros Occidental', contact: '(034) 474-0981', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Festive walk Iloilo', address: 'G/F Unit A25-A26, Festive Walk Mall, Brgy. Q. Abeto, Ilo-Ilo Buisness Park , Airport Road, Mandurriao, Ilo-Ilo City', contact: '(033) 517-7459', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Jaro Iloilo', address: 'North Diversion Road, Brgy. Dungon-B, Jaro,Ilo-Ilo City', contact: '(033) 327-2167 ', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Mandaue Cebu', address: 'UN Ave., Brgy. Umapad, Mandaue City, Cebu', contact: '(032) (032) 236-6413 ', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Sta Barbara Iloilo', address: 'Lot 506-B Brgy. Bolong Este, Sta. Barbara, Iloilo City', contact: '(033) 330-3605 ', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Tacloban', address: 'Purok Santol, Brgy. 80 Marasbaras, Tacloban City, Leyte', contact: '(053) 856-0151 / (053) 856-0152 / (053) 856-0153 ', active: 0} as StoreBranchModel,
        {type: 'VISAYAS', name: 'Talisay Cebu', address: 'Lot 2359, Lawa-an II, Talisay City, Cebu', contact: '(032) 505-0374 ', active: 0} as StoreBranchModel,
        
        {type: 'MINDANAO', name: 'Boalan Zamboanga', address: 'Lot 2235-C-1-A Boalan, Zamboanga City', contact: '(062) 957-1604 ', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'Butuan', address: 'Brgy. Baan Km3, Butuan City, Agusan Del Norte', contact: '(085) 956-0067 ', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'Cagayan De Oro', address: 'Zone 5, Brgy. Cugman Cagayan de Oro City, Misamis Oriental', contact: '(088) 859-2293 ', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'General Santos', address: 'Purok Palen, Brgy. Labangal, General Santos City', contact: '(083) 552-1880 ', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'Matina, Davao', address: 'Mc. Arthur Highway, Matina, Davao City', contact: '(082) 297-6936', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'Opol Misamis Oriental', address: 'Zone 2A, Barangay Barra, Opol, Cagayan De Oro, Misamis Oriental ', contact: '(088) 859-2280 ', active: 0} as StoreBranchModel,
        {type: 'MINDANAO', name: 'Panacan Davao', address: 'Block 2, Valle Verde, Panacan Diversion Rd. Davao City', contact: '(082) 285-8331 ', active: 0} as StoreBranchModel,
      ]},
    ];
  }
}
